### ISSUE TITLE
Neo4j 4.0 support

### ISSUE THREAD

**Issue by tomswinkels** [stefanak-michal/Bolt#1]
I know there is no documentation, but maybe you can look in to the official Neo4j drivers?

**Comment by jexp** [comment]
@stefanak-michal would you mind dropping me an email to michael at neo4j.com?

**Comment by stefanak-michal** [comment]
> I know there is no documentation, but maybe you can look in to the official Neo4j drivers?

I was thinking about this option. To dig it out from others. Frankly I don't have that required amount of time for that right now. :-/

**Comment by tomswinkels** [comment]
Did you have contact @jexp ? When i have time i will check if i can help with support for 4.0. Now i use the package of Graphaware.

**Comment by stefanak-michal** [comment]
@tomswinkels @jexp I've sended a contact to email in jexp github profile at 3.3.2020.

**Comment by tomswinkels** [comment]
Did you have response from @jexp ?

**Comment by stefanak-michal** [comment]
@tomswinkels I got no response.

**Comment by taliptako** [comment]
I also need this

**Comment by tim-hanssen** [comment]
It's hard to fix a driver without docs. Any progress on this?

**Comment by tomswinkels** [comment]
@stefanak-michal today there is a Neo4j Driver Contributor online meeting. Did you join that? Send a mail to michael at neo4j.com @jexp
