### ISSUE TITLE
Class 'Bolt\Bolt' not found

### ISSUE THREAD

**Issue by Alaizabel** [stefanak-michal/Bolt#10]
Hi,

awesome projectidea! I am looking very much for a new way to connect PHP to Neo4J 4.x. I tried your driver but it seems I do something wrong, maybe with the installation. When I open the index.php I run into 

`Fatal error: Uncaught Error: Class 'Bolt\Bolt' not found in C:\xampp\htdocs\Bolt-master\index.php:22`

Obviously I missed something in the setup - here is what I've done:

1. I unzipped the code into my htdocs
2. I checked my php.ini (XAMPP) and enabled 'extension=sockets' in my php.ini
3. I run the composer to make sure I have all what is needed with the result: 

`C:\xampp\htdocs\Bolt-master>composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Writing lock file
Generating autoload files`

4. I tested and it seems the index.page loads the "autoload.php" but crashes then when trying to use class BOLT.

Any idea what I made wrong?
Thank you

**Comment by stefanak-michal** [comment]
Hi.

I've tried your approach and you are right. I fixed autoload file.

https://github.com/stefanak-michal/Bolt/pull/16

**Comment by Alaizabel** [comment]
Perfect – thank you!

 

Von: Michal Štefaňák <notifications@github.com> 
Gesendet: Dienstag, 13. Oktober 2020 13:22
An: stefanak-michal/Bolt <Bolt@noreply.github.com>
Cc: Alaizabel <houlai@gmx.net>; Author <author@noreply.github.com>
Betreff: Re: [stefanak-michal/Bolt] Class 'Bolt\Bolt' not found (#10)

 

Hi.

I've tried your approach and you are right. I fixed autoload file.

#16 <https://github.com/stefanak-michal/Bolt/pull/16>
