### ISSUE TITLE
Run pull() directly after run()

### ISSUE THREAD

**Issue by tomswinkels** [stefanak-michal/Bolt#12]
Why i can't run pull() after run()?

I think it is better to do:

`$bolt->run('CREATE (a:Test) RETURN a, ID(a)')->pull();`

**Comment by stefanak-michal** [comment]
@tomswinkels I don't think chaining is required. How I explained in your other task, it's low level socket connection.

https://github.com/stefanak-michal/Bolt/issues/14

**Comment by stefanak-michal** [comment]
Also I forget, run() return false on error. It's important for situation when you use custom errorHandler and left the code continue, you have to verify it this way.

**Comment by stefanak-michal** [comment]
One last info, run() also returns meta informations about started query. Like bookmark or execution time.
