### ISSUE TITLE
ErrorException: socket_read(): unable to read from socket [4]: Interrupted system call

### ISSUE THREAD

**Issue by luutruong** [stefanak-michal/Bolt#17]
I have got some errors:

```
ErrorException: socket_read(): unable to read from socket [4]: Interrupted system call - (stripped)/vendor/stefanak-michal/bolt/Socket.php:136

#1  (stripped)/vendor/stefanak-michal/bolt/Socket.php(136): socket_read(Resource id #15, 2, 2)
#2  (stripped)/vendor/stefanak-michal/bolt/Socket.php(104): Bolt\Socket::readBuffer(2)
#3 (stripped)/vendor/stefanak-michal/bolt/protocol/V4.php(41): Bolt\Socket::read(Object(Bolt\PackStream\v1\Unpacker))
#4  (stripped)/vendor/stefanak-michal/bolt/protocol/V4.php(21): Bolt\protocol\V4->pull()
#5  (stripped)/vendor/stefanak-michal/bolt/Bolt.php(240): Bolt\protocol\V4->pullAll()
#6  (stripped)/Helper/DB.php(27): Bolt\Bolt->pull()

```

**Comment by stefanak-michal** [comment]
Hi.

I like to know a little more informations. 

- Where is running neo4j instance? (same pc as php application or different machine)
- What platform do you have? (linux, win, macos)
- What version of Neo4j do you have?
- How it looks your cypher query you call in ```run()``` before ```pull()```?

**Comment by luutruong** [comment]
`What version of Neo4j do you have?`
^1.1

`How it looks your cypher query you call in run() before pull()?`

This query i've used:
```
MATCH (u:User)-[:FOLLOWED]->(t:Tag)<-[:BELONG_TO]->(th)
WHERE u.user_id = %1$d AND NOT EXISTS((u)-[:READ]->(th))
WITH u.user_id AS user_id, th.thread_id AS thread_id,
                (0.5*th.like_count + 0.3*th.comment_count + 0.005*th.view_count
                    + duration.inDays(datetime(),datetime(th.published_date)).days*100) AS point
ORDER BY point desc
RETURN DISTINCT thread_id
LIMIT %2$d
```

**Comment by stefanak-michal** [comment]
Can I ask, what is this ```%1$d```? From Neo4j version 4 parameters are ```$name```. Do you have specific own parser for queries? 

https://neo4j.com/docs/cypher-manual/current/syntax/parameters/

If I change your query parameters to correct format and call it like this:
```php
$bolt = new \Bolt\Bolt();

if (!$bolt->init('MyClient/1.0', $user, $password)) {
    throw new Exception('Wrong login');
}

$bolt->run('MATCH (u:User)-[:FOLLOWED]->(t:Tag)<-[:BELONG_TO]->(th)
  WHERE u.user_id = $id AND NOT EXISTS((u)-[:READ]->(th))
  WITH u.user_id AS user_id, th.thread_id AS thread_id,
                (0.5*th.like_count + 0.3*th.comment_count + 0.005*th.view_count
                    + duration.inDays(datetime(),datetime(th.published_date)).days*100) AS point
  ORDER BY point desc
  RETURN DISTINCT thread_id
  LIMIT $limit', ['id' => 1, 'limit' => 2]);
var_dump($bolt->pull());
```

it returns (xdebug on), which is correct because last response entry is statistics:
```
D:\Programovanie - www\Bolt\index.php:37:
array (size=1)
  0 => 
    array (size=4)
      'bookmark' => string 'FB:kcwQCSYQnT3QRKyGhkGXdnJGHxyQ' (length=31)
      'type' => string 'r' (length=1)
      't_last' => int 0
      'db' => string 'neo4j' (length=5)
```

_I performed this code on Neo4j 4.1.1 and php 7.1.13_

Also there can be a problem with new format of parameters, which is double quote string in PHP. Because in double quoted string PHP is parsing variables with dollar sign.

**Comment by luutruong** [comment]
It's template then i fill params by using `sprintf` function.

**Comment by stefanak-michal** [comment]
Okay, I tried that with sprintf and it works. Doesn't seem problem is with query. This is first query you run or there is others before?

You can try turn on hex debug with ```\Bolt\Bolt::$debug = true;``` and post it here.

**Comment by luutruong** [comment]
I only run that query then pull. It's not 100% occurred that bug. I see some errors in prod not have issue on local dev.

**Comment by stefanak-michal** [comment]
I read something about that socket error and maybe you can try disable socket blocking, comment line 44 in Socket.php ```socket_set_block(Socket::$socket);```

**Comment by luutruong** [comment]
Is there anyway to check if that has been disabled?

**Comment by luutruong** [comment]
https://github.com/stefanak-michal/Bolt/blob/master/Socket.php#L44

I would suggest to check if we are successfully block.

```
if (socket_set_block(Socket::$socket) === false) {
    // throw some error due cannot block socket
}
```

**Comment by stefanak-michal** [comment]
I don't understand. Did you discover the blocking operation wasn't successful at the exception situation?

**Comment by luutruong** [comment]
At this moment. No.

**Comment by stefanak-michal** [comment]
I made some small upgrades to Socket.php. Catch error on set block mode how you suggested, also catch error on socket_read.

https://github.com/stefanak-michal/Bolt/commit/b813f198b3bfc7ff81625c615d9015d30bd70be4

**Comment by stefanak-michal** [comment]
If it happen only on production, how big is workload on it?

**Comment by luutruong** [comment]
It's still error.

**Comment by stefanak-michal** [comment]
By how you describe the problem it doesn't look like problem with this library, but it can be problem with your environment configuration. I'm just trying to help you identify your problem, I don't think I can solve it.

**Comment by luutruong** [comment]
@stefanak-michal i think so. I will update issue status when our server has some changes for this.
