### ISSUE TITLE
Remove Bolt:error(...) with exception?

### ISSUE THREAD

**Issue by luutruong** [stefanak-michal/Bolt#24]
Benifit:

- Clear code reading
- Easy catch with some specific error

Example with connection refused we can throw an exception like BoltConnectionException or when connect timeout BoltConnectionTimeoutException.

**Comment by stefanak-michal** [comment]
I'm not sure if I understand your idea. You want to get rid of using native Exception class and create extended classes?

I realize current errors are more likely programmer friendly, to understand what's wrong. Maybe it just need to add error codes to every error call?

**Comment by luutruong** [comment]
Example for this line: https://github.com/stefanak-michal/Bolt/blob/master/Bolt.php#L84

We can replace method `Bolt::error(...)` with `throw new LogicException('Requested PackStream version (' . $this->packStreamVersion . ') not yet implemented')` or `throw new BoltException('Requested PackStream version (' . $this->packStreamVersion . ') not yet implemented')`

**Comment by stefanak-michal** [comment]
If you don't call Bolt::error how you will call errorHandler instead of throwing exceptions?

**Comment by luutruong** [comment]
Other people can use with `try { ... } catch() {...}`

**Comment by stefanak-michal** [comment]
That means to change implementation. I'm using own errorHandler in every project with this library and I don't like the idea to change it everywhere.

**Comment by luutruong** [comment]
Maybe consider for further?

**Comment by stefanak-michal** [comment]
https://github.com/stefanak-michal/Bolt/tree/issue/24_remove_error_handler
