### ISSUE TITLE
Support some code standards checkers?

### ISSUE THREAD

**Issue by luutruong** [stefanak-michal/Bolt#28]
Popular:
- https://github.com/squizlabs/PHP_CodeSniffer
- https://github.com/FriendsOfPHP/PHP-CS-Fixer

**Comment by stefanak-michal** [comment]
These are not debuggers but more like cleaners. Debugger is for example xdebug. I'll take a look on them later.

**Comment by luutruong** [comment]
Php-cs-fixer is code clean
But phpsnipper help you fix some code logic. I have used them in many
projects
