### ISSUE TITLE
Update to composer package

### ISSUE THREAD

**Issue by tomswinkels** [stefanak-michal/Bolt#3]
Maybe nice to change it to a composer package.

**Comment by stefanak-michal** [comment]
Here is my opinion: _In theory composer and any package system are great. The idea to not worry about versions, updates and simple installation is amazing. But after all in real world there is a always issue with it. Isn't a software, is a code and that is the main core of problem. Personally I prefer manual installation of what I want._

But it really matters on my opinion? I made it here [composer](https://packagist.org/packages/stefanak-michal/bolt)
