### ISSUE TITLE
Unable to connect to Aura Hosted Neo4j Database

### ISSUE THREAD

**Issue by u12206050** [stefanak-michal/Bolt#38]
**Describe the bug**
I have tried different combinations of connection strings and versions, but can't get it to work.
It seems to be crashing inside the handshake function everytime. Looking at the socket read function it is just never ending with the content just being empty.

**To Reproduce**
Setup an aura database
Try connecting to it using the bolt protocol

**Expected behavior**
Connection should be established and handshake successful

**Desktop:**
 - OS: Ubuntu 20
 - PHP Version 7.4
 - Neo4j Version [e.g. 4.1.7
 - Bolt Library Version 4

**Comment by stefanak-michal** [comment]
Hi.

Propably aura required ssl. Can you try master branch of this library. There is a change about connection. It supports ssl with new connection class. 

Wiki is already updated to this change. https://github.com/stefanak-michal/Bolt/wiki/Connection 

You are interested about StreamSocket.

**Comment by u12206050** [comment]
Thanks, will try it out. Any chance of it being published as a new version soon?

**Comment by stefanak-michal** [comment]
Because I changed constructor of Bolt it has to be major update and I wanted to wait with more stuff to come in it. However let me now if this StreamSocket works for you. I don't have option to try Aura, it's only paid.

**Comment by u12206050** [comment]
This worked yes, thanks. Didn't even need the keys but worked setting
```
$conn->setSslContextOptions([
    'verify_peer' => true,
    'allow_self_signed' => true
]);
```
