### ISSUE TITLE
fread() is failing for me.

### ISSUE THREAD

**Issue by jonathan-rowley** [stefanak-michal/Bolt#45]
**Describe the bug**
I had issues using the Bolt protocol with some of my requests. it was intermittent which made it really difficult to troubleshoot. But i did find the issue and the fix.

**To Reproduce**
I don't know. it worked sometimes and not others.

**Expected behavior**
I expected my data to come back.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - PHP Version 7.4.3
 - Neo4j Version 4.1.3

**Additional context**

The Fix:
on file /src/connection/StreamSocket.php Line 95
the read() function fails sometimes.
I found this article helpful: https://stackoverflow.com/questions/14664409/fread-a-lot-slower-for-downloads-than-readfile

and then i changed this line:
```php
public function read(int $length = 2048): string
    {
        $res = fread($this->stream, $length); // <-- right here... fread fails a lot and now they recommend stream_get_contents()
        if (empty($res))
            throw new ConnectException('Read error');

        if (Bolt::$debug)
            $this->printHex($res, false);

        return (string)$res;
    }
```
to this:
```php
public function read(int $length = 2048): string
    {
        $res = stream_get_contents($this->stream, $length);
        if (empty($res))
            throw new ConnectException('Read error');

        if (Bolt::$debug)
            $this->printHex($res, false);

        return (string)$res;
    }
```
worked like a champ after that.

**Comment by stefanak-michal** [comment]
Hi.
Seems ok for me, can you make a pull request for that?

**Comment by jonathan-rowley** [comment]
ok, a bit embarrassing but this is my first time using github. i actually got your package installed via composer through this guy:
https://github.com/laudis-technologies/neo4j-php-client

i have GitKraken installed but have only used it for GitLabs for work. how do I do a pull request and what do i do from there?

**Comment by jonathan-rowley** [comment]
I just tried to do it through GitKraken and got access denied

**Comment by jonathan-rowley** [comment]
I think i figured it out. closing this issue now.
