### ISSUE TITLE
Use multiple databases

### ISSUE THREAD

**Issue by tomswinkels** [stefanak-michal/Bolt#8]
Since Neo4j 4.0 you can have multiple databases.

How can i use multiple databases with this package?

**Comment by stefanak-michal** [comment]
Selection of database is managed by extra parameters in RUN and BEGIN message. You can add extra parameters like this.

```php
$bolt->run('RETURN 1 as num', [], ['db' => 'database-name');
```

I didn't created extra parameters in managed way because they are extra. I don't think there is a need to use them often. Maybe in future I'll make them managed in some way.

**Comment by tomswinkels** [comment]
Plz add this to the documentation :)
